### ISSUE TITLE
消费者刚刚启动时消费会延时很长时间，多进程消费会有重复数据

### ISSUE THREAD

**Issue by 13686875631** [apache/rocketmq-client-cpp#100]
有2个问题，希望能得到各位的帮助，谢谢：
1.环境是多Master多Slave模式，同步双写，使用order模式生产和消费。消费者先启动，生产者发送数据，消费者需要等很长一段时间才能消费（差不多30秒），不知道什么原因？
2.多进程消费同一个topic时，发现偶尔有重复数据，不知道什么原因？

**Comment by ifplusor** [comment]
@13686875631 重复消息是无法避免的，须要在业务端做去重，或者业务幂等。
