### ISSUE TITLE
build error on CentOS7.4

### ISSUE THREAD

**Issue by BZever** [apache/rocketmq-client-cpp#107]
The issue tracker is **ONLY** used for the CPP/C client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
sh build.sh
- What did you expect to see?

- What did you see instead?
Linking CXX shared library ../../bin/librocketmq.so
../../bin/lib/libboost_locale.a ../../bin/lib/libboost_iostreams.a -ldl -lpthread -lrt -lz 
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[2]: *** [../bin/librocketmq.so] Error 1
make[2]: Leaving directory `/opt/rocketmq-client-cpp-1.2.1-rc1/tmp_build_dir'
make[1]: *** [project/CMakeFiles/rocketmq_shared.dir/all] Error 2
make[1]: Leaving directory `/opt/rocketmq-client-cpp-1.2.1-rc1/tmp_build_dir'
make: *** [all] Error 2

2. Please tell us about your environment:

 - What is your OS?
CentOS7.4
 - What is your client version?
1.2.1
 - What is your RocketMQ version?
4.4
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by jonnxu** [comment]
/usr/bin/ld: cannot find -lz

@BZever  you need install bzip library before build. please reference  README.md

Build and Install
note: make sure the following compile tools or libraries have been installed before running the build script build.sh.
compile tools:
gcc-c++ 4.8.2: c++ compiler while need support C++11
cmake 2.8.0: build jsoncpp require it
automake 1.11.1: build libevent require it
autoconf 2.65: build libevent require it
libtool 2.2.6: build libevent require it
libraries:
bzip2-devel 1.0.6: boost depend it

**Comment by BZever** [comment]
@jonnxu   thanks for your answer . now another error

Linking CXX executable ../../bin/AsyncProducer
cd /opt/rocketmq-client-cpp/tmp_build_dir/example && /usr/bin/cmake -E cmake_link_script CMakeFiles/AsyncProducer.dir/link.txt --verbose=1
/usr/bin/c++   -Wall -Wno-deprecated -fPIC -fno-strict-aliasing -std=c++11 -Wno-unused-local-typedef -Wno-expansion-to-defined -m64 -O3 -DNDEBUG    CMakeFiles/AsyncProducer.dir/AsyncProducer.cpp.o  -o ../../bin/AsyncProducer  -L/opt/rocketmq-client-cpp/bin/lib -rdynamic ../../bin/librocketmq.so ../../libs/signature/lib/libSignature.a ../../bin/lib/libjsoncpp.a ../../bin/lib/libevent.a ../../bin/lib/libevent_core.a ../../bin/lib/libevent_extra.a ../../bin/lib/libevent_pthreads.a ../../bin/lib/libboost_atomic.a ../../bin/lib/libboost_thread.a ../../bin/lib/libboost_system.a ../../bin/lib/libboost_chrono.a ../../bin/lib/libboost_date_time.a ../../bin/lib/libboost_log.a ../../bin/lib/libboost_log_setup.a ../../bin/lib/libboost_regex.a ../../bin/lib/libboost_serialization.a ../../bin/lib/libboost_filesystem.a ../../bin/lib/libboost_locale.a ../../bin/lib/libboost_iostreams.a -ldl -lpthread -lrt -lz -Wl,-rpath,/opt/rocketmq-client-cpp/bin/lib:/opt/rocketmq-client-cpp/bin 
../../bin/librocketmq.so: undefined reference to `boost::iostreams::zlib::deflated'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::detail::zlib_base::before(char const*&, char const*, char*&, char*)'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::zlib_error::check(int)'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::detail::zlib_base::xdeflate(int)'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::detail::zlib_base::reset(bool, bool)'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::zlib::stream_end'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::zlib::no_flush'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::detail::zlib_base::xinflate(int)'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*)'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::detail::zlib_base::zlib_base()'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::detail::zlib_base::~zlib_base()'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::zlib::default_strategy'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::zlib::sync_flush'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool)'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::zlib::finish'
../../bin/librocketmq.so: undefined reference to `boost::iostreams::zlib::default_compression'

**Comment by elisium7** [comment]
> @jonnxu   thanks for your answer . now another error
> Linking CXX executable ../../bin/AsyncProducer
> cd /opt/rocketmq-client-cpp/tmp_build_dir/example && /usr/bin/cmake -E cmake_link_script CMakeFiles/AsyncProducer.dir/link.txt --verbose=1
> /usr/bin/c++   -Wall -Wno-deprecated -fPIC -fno-strict-aliasing -std=c++11 -Wno-unused-local-typedef -Wno-expansion-to-defined -m64 -O3 -DNDEBUG    CMakeFiles/AsyncProducer.dir/AsyncProducer.cpp.o  -o ../../bin/AsyncProducer  -L/opt/rocketmq-client-cpp/bin/lib -rdynamic ../../bin/librocketmq.so ../../libs/signature/lib/libSignature.a ../../bin/lib/libjsoncpp.a ../../bin/lib/libevent.a ../../bin/lib/libevent_core.a ../../bin/lib/libevent_extra.a ../../bin/lib/libevent_pthreads.a ../../bin/lib/libboost_atomic.a ../../bin/lib/libboost_thread.a ../../bin/lib/libboost_system.a ../../bin/lib/libboost_chrono.a ../../bin/lib/libboost_date_time.a ../../bin/lib/libboost_log.a ../../bin/lib/libboost_log_setup.a ../../bin/lib/libboost_regex.a ../../bin/lib/libboost_serialization.a ../../bin/lib/libboost_filesystem.a ../../bin/lib/libboost_locale.a ../../bin/lib/libboost_iostreams.a -ldl -lpthread -lrt -lz -Wl,-rpath,/opt/rocketmq-client-cpp/bin/lib:/opt/rocketmq-client-cpp/bin
> ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::deflated' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::before(char const*&, char const*, char*&, char*)'
> ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib_error::check(int)' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::xdeflate(int)'
> ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::reset(bool, bool)' ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::stream_end'
> ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::no_flush' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::xinflate(int)'
> ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*)' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::zlib_base()'
> ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::~zlib_base()' ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::default_strategy'
> ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::sync_flush' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool)'
> ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::finish' ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::default_compression'

I met the same error before,that's because you have some errors when you build the boost_iostreams with lack of zlib.you can remove the boost libs and then rebuild them.

i

**Comment by wangwenqiangGitHub** [comment]
> > @jonnxu   thanks for your answer . now another error
> > Linking CXX executable ../../bin/AsyncProducer
> > cd /opt/rocketmq-client-cpp/tmp_build_dir/example && /usr/bin/cmake -E cmake_link_script CMakeFiles/AsyncProducer.dir/link.txt --verbose=1
> > /usr/bin/c++   -Wall -Wno-deprecated -fPIC -fno-strict-aliasing -std=c++11 -Wno-unused-local-typedef -Wno-expansion-to-defined -m64 -O3 -DNDEBUG    CMakeFiles/AsyncProducer.dir/AsyncProducer.cpp.o  -o ../../bin/AsyncProducer  -L/opt/rocketmq-client-cpp/bin/lib -rdynamic ../../bin/librocketmq.so ../../libs/signature/lib/libSignature.a ../../bin/lib/libjsoncpp.a ../../bin/lib/libevent.a ../../bin/lib/libevent_core.a ../../bin/lib/libevent_extra.a ../../bin/lib/libevent_pthreads.a ../../bin/lib/libboost_atomic.a ../../bin/lib/libboost_thread.a ../../bin/lib/libboost_system.a ../../bin/lib/libboost_chrono.a ../../bin/lib/libboost_date_time.a ../../bin/lib/libboost_log.a ../../bin/lib/libboost_log_setup.a ../../bin/lib/libboost_regex.a ../../bin/lib/libboost_serialization.a ../../bin/lib/libboost_filesystem.a ../../bin/lib/libboost_locale.a ../../bin/lib/libboost_iostreams.a -ldl -lpthread -lrt -lz -Wl,-rpath,/opt/rocketmq-client-cpp/bin/lib:/opt/rocketmq-client-cpp/bin
> > ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::deflated' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::before(char const*&, char const*, char*&, char*)'
> > ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib_error::check(int)' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::xdeflate(int)'
> > ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::reset(bool, bool)' ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::stream_end'
> > ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::no_flush' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::xinflate(int)'
> > ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (_)(void_, unsigned int, unsigned int), void (_)(void_, void*), void*)' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::zlib_base()'
> > ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::~zlib_base()' ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::default_strategy'
> > ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::sync_flush' ../../bin/librocketmq.so: undefined reference to boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool)'
> > ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::finish' ../../bin/librocketmq.so: undefined reference to boost::iostreams::zlib::default_compression'
> 
> I met the same error before,that's because you have some errors when you build the boost_iostreams with lack of zlib.you can remove the boost libs and then rebuild them.
> 
> i

I have build boost_iostreams with zlib ,but still this question
