### ISSUE TITLE
Can not build using Visual Studio 2017

### ISSUE THREAD

**Issue by goldenbull** [apache/rocketmq-client-cpp#120]
win32_build.bat is hardcoded for Visual Studio 2015.
It's better to support both 2015 and 2017.

**Comment by ShannonDing** [comment]
Could you please help to optimize this compile process in Windows platform?

**Comment by hugoasdf** [comment]
> 
> 
> win32_build.bat is hardcoded for Visual Studio 2015.
> It's better to support both 2015 and 2017.

yes，currently vs2015 is recommended and directly support by build script.as wished,next we will test code compilation beheavior with vs2017.then,build script will support VS150COMNTOOLS.
