### ISSUE TITLE
Can not build x64 version using visual studio.

### ISSUE THREAD

**Issue by hl1282456555** [apache/rocketmq-client-cpp#122]
Do you have any plans to support build x64 version?

Or can you tell me how to change the source to support build x64 version?

**Comment by hugoasdf** [comment]
x86_64 build support commited already，just change build input paramater.

**Comment by hl1282456555** [comment]
I tried to change the input parameter to build x86_64, it can build success.
but if I use the lib in my project, I got many errors.

Can you give me some guides?

**Comment by hugoasdf** [comment]
> "build success" the example exe file run in 32bits address model or in 64bits mode?
> if the generated binary file is x86_64 format,"use the lib in my project" error may because of project config.what is the errors?
> 
> I tried to change the input parameter to build x86_64, it can build success.
> but if I use the lib in my project, I got many errors.
> 
> Can you give me some guides?

**Comment by hl1282456555** [comment]
I change the build config to generate an x64 binary file because the sln file did not support x64 address model.

I do not remember what the errors. I am using the activemq for my demo project now.

If my memory is right, there are many errors of the macro.

I'll try to build the binary file again.

Then I'll commit the errors to here.
