### ISSUE TITLE
Question about onsChannel param

### ISSUE THREAD

**Issue by messense** [apache/rocketmq-client-cpp#124]
What does `onsChannel` param mean in `setSessionCredentials` method?

https://github.com/apache/rocketmq-client-cpp/blob/a42078df3d538f88e32539f537c5d5a3c17aaf4c/include/MQClient.h#L174-L176

**Comment by ShannonDing** [comment]
This method provides the ability to connect some cloud platform with your AK, SK using a specific signature, such as aliyun and so on. eg, "ALIYUN" should be set to the Channel and the c style API  is recommend to use like `ROCKETMQCLIENT_API int SetProducerSessionCredentials(CProducer *producer, const char *accessKey, const char *secretKey,const char *onsChannel);`

**Comment by messense** [comment]
If I setup authentication for my local RocketMQ instance, can I use `setSessionCredentials` method? How should I pass `onsChannel` param in that case?

**Comment by ShannonDing** [comment]
Just leave them none, if you wanna connect local broker without authentication.

**Comment by messense** [comment]
Did you mean **with authentication**?

**Comment by vongosling** [comment]
@ShannonDing I think you should make some clear when supporting some cloud service.

**Comment by ShannonDing** [comment]
1. Connect Aliyun:  please fulfill the paras with AK, SK and "ALIYUN",
2. Connect local broker without authentication: leave all the paras of SessionCredentials none,
3. Connect local broker with authentication: using AK, SK, and your signature method name instead now,
4. Other could platform: not support now

**Comment by messense** [comment]
@ShannonDing Thanks!
