### ISSUE TITLE
How to concurrent pull msg?

### ISSUE THREAD

**Issue by yichenluan** [apache/rocketmq-client-cpp#141]
I want to use 'DefaultMQPullConsumer:: pull'  in my code, but what's the best practice for supporting concurrent pull?

Now, I'm using multi-thread which shares one client instance, (example: std::shared_ptr<DefaultMQPullConsumer>), is it right? any suggestion?

Also, I want to concurrent produce msgs, but this one, I believe just multi-thread is good enough.

Thanks.

**Comment by yichenluan** [comment]
@ShannonDing @jonnxu @ifplusor 
please help me

**Comment by ifplusor** [comment]
i think best practice is DefaultMQPushConsumer with CLUSTERING model, the essence of it is allocate queue between all client instances and pull messages from these queues. you can allocate queues by your strategy, one thread to many queues, or share thread pool like DefaultMQPushConsumer and consume in another thread pool.
concurrent produce is easy.

**Comment by yichenluan** [comment]
> i think best practice is DefaultMQPushConsumer with CLUSTERING model, the essence of it is allocate queue between all client instances and pull messages from these queues. you can allocate queues by your strategy, one thread to many queues, or share thread pool like DefaultMQPushConsumer and consume in another thread pool.
> concurrent produce is easy.

@ifplusor   Thanks, But I have to use PullConsumer, because I need to manage consume offset manually and in broadcast mode  in my case.

Any idea of concurrently pull msgs?  Thank you anyway

**Comment by ifplusor** [comment]
@yichenluan share thread pool for queues of topic, but only one pull task for a certain queue in your task queue.
