### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by huqiuyun** [apache/rocketmq-client-cpp#148]
[bug] NameSpaceUtil::formatNameServerURL
    unsigned int index = nameServerAddr.find(ENDPOINT_PREFIX);
    if (index != string::npos) 

right:

    int index = nameServerAddr.find(ENDPOINT_PREFIX);
    if (index != string::npos) 

exmaple:
    setNamesrvAddr("122.12.122.122:8080) , result: 122.122:8080

**Comment by ShannonDing** [comment]
same as #142

**Comment by ifplusor** [comment]
fixed by PR #143
