### ISSUE TITLE
async send exist a small mistake

### ISSUE THREAD

**Issue by MemeTao** [apache/rocketmq-client-cpp#150]
我遇到这样几点问题：
1. 如果消息服务未部署，producer.start() 不抛异常（最好有可以获取状态的东西）
2. 如果消息服务地址无法ping通（由于网络或是其它原因），异步发送接口 producer.send(mess,callback) 将会阻塞。

**Comment by ifplusor** [comment]
因为 dns 解析和创建 socket 都是同步的，这里会产生阻塞。

**Comment by ShannonDing** [comment]
close due to time too long.
a new issue is welcomed.
