### ISSUE TITLE
build error on Windows

### ISSUE THREAD

**Issue by bq49** [apache/rocketmq-client-cpp#153]
win32_build.bat build
.......
`
D:\Work\rocketmq-client-cpp\Win32\AsyncPushConsumer.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\AsyncPushConsumer.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\OrderlyPushConsumer.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\OrderlyPushConsumer.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\COrderlyAsyncProducer.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\COrderlyAsyncProducer.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\OrderProducer.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\OrderProducer.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\Producer.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\Producer.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\PullConsumer.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\PullConsumer.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\PushConsumeMessage.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\PushConsumeMessage.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\PushConsumer.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\PushConsumer.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\SendDelayMsg.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\SendDelayMsg.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\SyncProducer.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\SyncProducer.vcxproj" could not be found.

D:\Work\rocketmq-client-cpp\Win32\AsyncProducer.vcxproj : error  : Project "D:\Work\rocketmq-client-cpp\Win32\AsyncProducer.vcxproj" could not be found.

1>------ Build started: Project: rocketmq-client-cpp, Configuration: Release x64 ------
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(367,5): warning MSB8004: Intermediate Directory does not end with a trailing slash.  This build instance will add the slash as it is required to allow proper evaluation of the Intermediate Directory.
1>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification
1>LINK : fatal error LNK1181: cannot open input file 'D:\Work\rocketmq-client-cpp\Win32\..\thirdparty\libevent-release-2.0.22\x64\Release\libevent.lib'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by doodoocoder** [comment]
suggest use ms2015 gui not command better

**Comment by ShannonDing** [comment]
link #120

**Comment by ShannonDing** [comment]
close due to time too long.
