### ISSUE TITLE
build error on centos

### ISSUE THREAD

**Issue by bq49** [apache/rocketmq-client-cpp#155]
Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Tue Aug 22 21:09:27 UTC 2017

gcc.compile.c++ bin.v2/libs/iostreams/build/gcc-4.8.5/release/link-static/threading-multi/bzip2.o
libs/iostreams/src/bzip2.cpp:20:56: fatal error: bzlib.h: No such file or directory
 #include "bzlib.h"  // Julian Seward's "bzip.h" header.
                                                        ^
compilation terminated.

    "g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pthread -m64 -fPIC -fPIC -DBOOST_ALL_NO_LIB=1 -DBOOST_IOSTREAMS_USE_DEPRECATED -DNDEBUG  -I"." -c -o "bin.v2/libs/iostreams/build/gcc-4.8.5/release/link-static/threading-multi/bzip2.o" "libs/iostreams/src/bzip2.cpp"

...failed gcc.compile.c++ bin.v2/libs/iostreams/build/gcc-4.8.5/release/link-static/threading-multi/bzip2.o...
...skipped <pbin.v2/libs/iostreams/build/gcc-4.8.5/release/link-static/threading-multi>libboost_iostreams.a(clean) for lack of <pbin.v2/libs/iostreams/build/gcc-4.8.5/release/link-static/threading-multi>bzip2.o...
...skipped <pbin.v2/libs/iostreams/build/gcc-4.8.5/release/link-static/threading-multi>libboost_iostreams.a for lack of <pbin.v2/libs/iostreams/build/gcc-4.8.5/release/link-static/threading-multi>bzip2.o...
...skipped <p/work/rocketmq-client-cpp/bin/lib>libboost_iostreams.a for lack of <pbin.v2/libs/iostreams/build/gcc-4.8.5/release/link-static/threading-multi>libboost_iostreams.a...
...failed updating 1 target...
...skipped 3 targets...

**Comment by ShannonDing** [comment]
the bzip2-devel package should be installed before boost was compiled.

**Comment by bq49** [comment]
> the bzip2-devel package should be installed before boost was compiled.

Thank you ShannonDing, It's work.
