### ISSUE TITLE
How to use latest version of boost in my project ?

### ISSUE THREAD

**Issue by yichenluan** [apache/rocketmq-client-cpp#161]
I want to use boost::beast, that means I have to include latest boost.

But after I include it, my binary crashes(segment fault) when shut down DefaultPullConsumer...

**Comment by ifplusor** [comment]
We will delete the dependence of boost in the coming months. You need modify build.sh or CMakeLists.txt to link latest boost library.

**Comment by jonnxu** [comment]
if you want to use your own boost version, please modify the build.sh
