### ISSUE TITLE
Nothing happened to start a consumer even if I setup a non-exist nameserver address

### ISSUE THREAD

**Issue by zhangyulu** [apache/rocketmq-client-cpp#164]
I wrote a simple PushConsumer based on example/PushConsumer.cpp. I typed  a wrong nameserver port(nameserver listen on port 9876 as default), but nothing happened, no any exceptions, and I checked the DefaultMQPushConsumer::start() is a void method, so how should I detect this kind of errors? Thanks
The code shows below:

```
#include <stdlib.h>
#include <string.h>

#include <chrono>
#include <iomanip>
#include <iostream>
#include <map>
#include <string>
#include <vector>
#include <thread>

#include "DefaultMQPushConsumer.h"

using namespace rocketmq;
using namespace std;

class MyMsgListener : public MessageListenerConcurrently {
 public:
  MyMsgListener() {}
  virtual ~MyMsgListener() {}

  virtual ConsumeStatus consumeMessage(const std::vector<MQMessageExt>& msgs) {
    for (auto& msg : msgs) {
      cout << "msg body: "<<  msg.getBody() << endl;
    }
    return CONSUME_SUCCESS;
  }
};

int main(int argc, char* argv[]) {
  DefaultMQPushConsumer consumer("zyl_consumer_group");
  consumer.setNamesrvAddr("192.168.1.102:9875");

  consumer.setConsumeThreadCount(1);
  consumer.setConsumeFromWhere(CONSUME_FROM_LAST_OFFSET);

  consumer.subscribe("test-topic", "*");
  //consumer.setTcpTransportTryLockTimeout(1000);
  //consumer.setTcpTransportConnectTimeout(400);

  MyMsgListener msglistener;
  consumer.registerMessageListener(&msglistener);

  try {
    consumer.start();
  } catch (MQClientException& e) {
    cout << e << endl;
    return -1;
  }

  while (1) {
      std::this_thread::sleep_for(std::chrono::seconds(1));
  }
  consumer.shutdown();
  return 0;
}
```

**Comment by ifplusor** [comment]
wrong namesrv address don't cause any exception.

**Comment by ifplusor** [comment]
but you can check log files.

**Comment by ShannonDing** [comment]
For historical reasons， this API was designed as a non-return method.
IMO, the name server address is a key parameter of the client, for time being, it is better for users to check it carefully. 
and take a step back, a wrong ns address should not block the start process of a client, it will throw a "no topic route" exception when sending messages. 
sometimes，the ns will be set to a VIP or a domain, the client will work normally as soon as the name server is OK.
