### ISSUE TITLE
Add build64 on windows

### ISSUE THREAD

**Issue by doodoocoder** [apache/rocketmq-client-cpp#166]
when using rocketmq-client-cpp.sln with visual studio 2015 to build rocket-client-cpp.dll ,everything is done  except 3 link errors :

1.	cant resovle the external symbol  ,MQClient.obj ,like following:
"public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl rocketmq::NameSpaceUtil::formatNameServerURL(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?formatNameServerURL@NameSpaceUtil@rocketmq@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V34@@Z)，该符号在函数 "public: void __cdecl rocketmq::MQClient::setNamesrvAddr(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?setNamesrvAddr@MQClient@rocketmq@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)

2.  cant resovle the external symbol  ,DefaultMQProducer.obj,like following:
"public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl rocketmq::BatchMessage::encode(class std::vector<class rocketmq::MQMessage,class std::allocator<class rocketmq::MQMessage> > &)" (?encode@BatchMessage@rocketmq@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAV?$vector@VMQMessage@rocketmq@@V?$allocator@VMQMessage@rocketmq@@@std@@@4@@Z)，该符号在函数 "protected: class rocketmq::BatchMessage __cdecl rocketmq::DefaultMQProducer::buildBatchMessage(class std::vector<class rocketmq::MQMessage,class std::allocator<class rocketmq::MQMessage> > &)" (?buildBatchMessage@DefaultMQProducer@rocketmq@@IEAA?AVBatchMessage@2@AEAV?$vector@VMQMessage@rocketmq@@V?$allocator@VMQMessage@rocketmq@@@std@@@std@@@Z) 中被引用	rocketmq-client-cpp		

3. cant resovle the external symbol  ,TcpTransport.obj,like following:
 "public: static class rocketmq::EventLoop * __cdecl rocketmq::EventLoop::GetDefaultEventLoop(void)" (?GetDefaultEventLoop@EventLoop@rocketmq@@SAPEAV12@XZ)，该符号在函数 "public: enum rocketmq::TcpConnectStatus __cdecl rocketmq::TcpTransport::connect(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int)" (?connect@TcpTransport@rocketmq@@QEAA?AW4TcpConnectStatus@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z) 中被引用	rocketmq-client-cpp	E:\rocket-x\rocketmq-client-cpp-master\Win32\TcpTransport.obj	
who can tell me how to fix?

**Comment by ShannonDing** [comment]
close due to time to long.
