### ISSUE TITLE
大神们，这个图片中的错误怎么解决？

### ISSUE THREAD

**Issue by doodoocoder** [apache/rocketmq-client-cpp#168]
![image](https://user-images.githubusercontent.com/26543224/61679022-6b820380-ad37-11e9-9cf5-dbc9e989cdc4.png)
在vs2015里该加的头文件目录都加了，比如根目录中的include目录，目前还是这个错误。以前是报缺少库文件，然后就装json库，libevent库，只差最后这个问题了，纠结一个星期了。
HELP ME!!
HELP ME!!
HELP ME!!

**Comment by ifplusor** [comment]
@hugoasdf

**Comment by doodoocoder** [comment]
@hugoasdf 我试过了，一样的。这个项目不完整，与原来的项目相比，连win32都没有
