### ISSUE TITLE
Prebuild CPP binary mirror needed

### ISSUE THREAD

**Issue by XadillaX** [apache/rocketmq-client-cpp#173]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

I think we need a mirror and an index to record each platform's prebuild CPP SDK binary libraries for each version.

Any official planning for it? Thanks.

2. Provide any additional detail on your proposed use case for this feature.

To avoid the whole project compiling by each developers and save time.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

Each language (Go, Python and Node.js) has the prebuild way to setup the SDK. But there's no clear and standardized way.

**Comment by ShannonDing** [comment]
Good idea!
It is planned to release binary packages since version1.2.3 in this month and after it releases, the package can be downloaded from both GitHub release tag and the apache repository.

**Comment by ShannonDing** [comment]
close due to 1.2.3 being release.

**Comment by XadillaX** [comment]
It means this is finished?

**Comment by ShannonDing** [comment]
According to the release process, all the issues under the label 1.2.3 should be closed first. and now, this release is under the voting process and will be released soon.
For detail info about this release, you can refer to http://rocketmq.apache.org/release_notes/release-notes-rocketmq-client-cpp-1.2.3/

**Comment by wohenbushuang** [comment]
request for binary version for ubuntu, alpine. Failed to build from source on both OS
