### ISSUE TITLE
About mq offset in C API

### ISSUE THREAD

**Issue by neo1104** [apache/rocketmq-client-cpp#182]
when i use pull mode in C API, i found mq offset can not  sync with broker, every time i restart the client , i recevie all the history message.  Is this right? Do I need have to   maintain the mq offset myself?

Please help me ,thank you .

**Comment by jonnxu** [comment]
for pull model, it need you to maintain the offset, you need update the offset by timer

**Comment by jonnxu** [comment]
@neo1104

**Comment by ShannonDing** [comment]
call for a discussion: shall we support a C API to save the offset to local file or update offset to remote broker?
