### ISSUE TITLE
sh build.sh err: -Wunused-private-field

### ISSUE THREAD

**Issue by dreaminglwj** [apache/rocketmq-client-cpp#184]
mac os:10.13.6 (17G8030)
g++:4.9.2

[ 20%] Building CXX object project/CMakeFiles/rocketmq_static.dir/__/src/transport/TcpRemotingClient.cpp.o
cd /Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/tmp_build_dir/project && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/bin/include -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/bin/include/jsoncpp -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/include -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/common -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/consumer -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/extern -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/log -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/message -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/producer -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/protocol -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/thread -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/transport -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src -I/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/libs/signature/include  -Wall -Wno-deprecated -fPIC -fno-strict-aliasing -std=c++11 -Wno-unused-local-typedef -Wno-expansion-to-defined -m64 -O3 -DNDEBUG   -o CMakeFiles/rocketmq_static.dir/__/src/transport/TcpRemotingClient.cpp.o -c /Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/transport/TcpRemotingClient.cpp
2 errors generated.
make[2]: *** [project/CMakeFiles/rocketmq_static.dir/__/src/transport/EventLoop.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/transport/ResponseFuture.cpp:17:
/Users/luwenjin/Documents/work/cppSrc/github.com/rocketmq-client-cpp/src/transport/ResponseFuture.h:83:23: warning: private field
      'm_asyncCallbackStatus' is not used [-Wunused-private-field]
  AsyncCallbackStatus m_asyncCallbackStatus;
                      ^
1 warning generated.
make[1]: *** [project/CMakeFiles/rocketmq_shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [project/CMakeFiles/rocketmq_static.dir/all] Error 2
make: *** [all] Error 2

**Comment by ifplusor** [comment]
@dreaminglwj Could you post more detail?

**Comment by bingwei** [comment]
more detail from what I got.
rocketmq-client-cpp: 2.1.0
boost_1_77_0.tar.gz
libevent-release-2.1.11-stable.zip
jsoncpp-0.10.7.zip
-------


[ 64%] Building CXX object project/CMakeFiles/rocketmq_static.dir/__/src/producer/TransactionMQProducerImpl.cpp.o
cd /Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/tmp_build_dir/project && /Library/Developer/CommandLineTools/usr/bin/c++  -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/bin/include -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/bin/include/jsoncpp -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/include -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/common -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/consumer -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/extern -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/include -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/log -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/message -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/producer -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/protocol -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/thread -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/trace -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/transport -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src -I/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/libs/signature/include -Wall -Wno-deprecated -fPIC -fno-strict-aliasing -std=c++11 -Wno-unused-local-typedef -Wno-expansion-to-defined -m64 -O3 -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk -MD -MT project/CMakeFiles/rocketmq_static.dir/__/src/producer/TransactionMQProducerImpl.cpp.o -MF CMakeFiles/rocketmq_static.dir/__/src/producer/TransactionMQProducerImpl.cpp.o.d -o CMakeFiles/rocketmq_static.dir/__/src/producer/TransactionMQProducerImpl.cpp.o -c /Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/producer/TransactionMQProducerImpl.cpp
1 error generated.
make[2]: *** [project/CMakeFiles/rocketmq_static.dir/__/src/producer/StringIdMaker.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 warning generated.
1 warning generated.
In file included from /Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/producer/TransactionMQProducer.cpp:21:
In file included from /Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/producer/TransactionMQProducerImpl.h:23:
/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/bin/include/boost/bind.hpp:36:1: warning: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior. [-W#pragma-messages]
BOOST_PRAGMA_MESSAGE(
^
/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/bin/include/boost/config/pragma_message.hpp:24:34: note: expanded from macro 'BOOST_PRAGMA_MESSAGE'
# define BOOST_PRAGMA_MESSAGE(x) _Pragma(BOOST_STRINGIZE(message(x)))
                                 ^
<scratch space>:393:2: note: expanded from here
 message("The practice of declaring the Bind placeholders (_1, _2, ...) " "in the global namespace is deprecated. Please use " "<boost/bind/bind.hpp> + using namespace boost::placeholders, " "or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.")
 ^
In file included from /Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/producer/TransactionMQProducerImpl.cpp:18:
In file included from /Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/src/producer/TransactionMQProducerImpl.h:23:
/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/bin/include/boost/bind.hpp:36:1: warning: The practice of declaring the Bind placeholders (_1, _2, ...) in the global namespace is deprecated. Please use <boost/bind/bind.hpp> + using namespace boost::placeholders, or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior. [-W#pragma-messages]
BOOST_PRAGMA_MESSAGE(
^
/Users/bj00137ml/temp/rocketmq-client-install/rocketmq-client-cpp-2.1.0/bin/include/boost/config/pragma_message.hpp:24:34: note: expanded from macro 'BOOST_PRAGMA_MESSAGE'
# define BOOST_PRAGMA_MESSAGE(x) _Pragma(BOOST_STRINGIZE(message(x)))
                                 ^
<scratch space>:185:2: note: expanded from here
 message("The practice of declaring the Bind placeholders (_1, _2, ...) " "in the global namespace is deprecated. Please use " "<boost/bind/bind.hpp> + using namespace boost::placeholders, " "or define BOOST_BIND_GLOBAL_PLACEHOLDERS to retain the current behavior.")
 ^
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
make[1]: *** [project/CMakeFiles/rocketmq_static.dir/all] Error 2
make: *** [all] Error 2
build error.....
