### ISSUE TITLE
How to compile rocketmq-cpp in aarch64/arm ?

### ISSUE THREAD

**Issue by nehczy** [apache/rocketmq-client-cpp#194]

**Comment by ifplusor** [comment]
We don’t test the client in arm platform, but you can do this same as x86 platform, and post result here.

**Comment by nehczy** [comment]
> We don’t test the client in arm platform, but you can do this same as x86 platform, and post result here.

After run build.sh, the libboost compile failed. 
 
"g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pthread -m64 -fPIC -fPIC -DBOOST_ALL_NO_LIB=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/serialization/build/gcc-4.8.5/release/link-static/threading-multi/xml_wgrammar.o" "libs/serialization/src/xml_wgrammar.cpp"

...failed gcc.compile.c++ bin.v2/libs/serialization/build/gcc-4.8.5/release/link-static/threading-multi/xml_wgrammar.o...
gcc.compile.c++ bin.v2/libs/serialization/build/gcc-4.8.5/release/link-static/threading-multi/xml_wiarchive.o
g++: error：unrecognized command line option ‘-m64’

    "g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pthread -m64 -fPIC -fPIC -DBOOST_ALL_NO_LIB=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/serialization/build/gcc-4.8.5/release/link-static/threading-multi/xml_wiarchive.o" "libs/serialization/src/xml_wiarchive.cpp"

...failed gcc.compile.c++ bin.v2/libs/serialization/build/gcc-4.8.5/release/link-static/threading-multi/xml_wiarchive.o...
gcc.compile.c++ bin.v2/libs/serialization/build/gcc-4.8.5/release/link-static/threading-multi/xml_woarchive.o
g++: error：unrecognized command line option ‘-m64’

    "g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pthread -m64 -fPIC -fPIC -DBOOST_ALL_NO_LIB=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/serialization/build/gcc-4.8.5/release/link-static/threading-multi/xml_woarchive.o" "libs/serialization/src/xml_woarchive.cpp"

...failed gcc.compile.c++ bin.v2/libs/serialization/build/gcc-4.8.5/release/link-static/threading-multi/xml_woarchive.o...
gcc.compile.c++ bin.v2/libs/serialization/build/gcc-4.8.5/release/link-static/threading-multi/codecvt_null.o
g++: error：unrecognized command line option ‘-m64’

**Comment by ShannonDing** [comment]
close due to time to long.
