### ISSUE TITLE
zlib-devel should be installed before run build.sh

### ISSUE THREAD

**Issue by onexianjian** [apache/rocketmq-client-cpp#200]
zlib-devel 这个库在centos7下也必须先安装才可以运行build.sh。否则不但本次链接不通过。就算后面装了这个库再次执行build.sh 编译示例的时候就会一直提示链接失败。所以请一定在文档中把它和bzip2-devel写在一起。需且一定要先装完之后再运行build.sh

**Comment by ShannonDing** [comment]
Could you please create a PR about it?

**Comment by ShannonDing** [comment]
done
