### ISSUE TITLE
rabbitMQ服务端重启之后，已经订阅的消费者的重新订阅问题

### ISSUE THREAD

**Issue by panyongxuan** [apache/rocketmq-client-cpp#203]
在消费者(MQPushConsumer)向rabbitMQ服务端订阅成功后，重启服务器，发现消费者无法获取到订阅的信息。
请问库中提供了类似自动重连订阅之类的功能吗？
或者怎么能获取到服务器连接断开的动作，有服务器连接断开的之类回调函数吗？

**Comment by ShannonDing** [comment]
Welcome to the Apache RocketMQ community and you can have a try on [RockwtMQ.](https://github.com/apache/rocketmq) 
IMO, for this issue, you'd better ask somebody in the rabbitmq community to get a quick response.
