### ISSUE TITLE
PushConsumer reconnection exception

### ISSUE THREAD

**Issue by panyongxuan** [apache/rocketmq-client-cpp#204]
场景描述（1、2、3、 4 正常，5-6有异议），步骤如下：
1.rocketMQ服务器正常运行
2.通过C接口的CPushConsumer对象连接服务器并订阅（连接和订阅成功）
3.通过mqshutdown 停止broker和namesrv
4.查看日志，发现库在的socket一直在循环尝试重新连接（大约1分钟内一直重复try to connect、invokeAsync failed、pullMessageAsync failed of addr、eventcb: received error 、can not connect to server、disconnect等重连操作）
5.超过一段时间（本机是1分钟左右）后，就停止重连操作了（最后卡在“disconnect:10.110.9.100:10911 start. event:0x7f6eac007c20[disconnect:135]”上，没有相应的:disconnect:10.110.9.100:10911 completely[disconnect:138]，之后也没有try to connect等操作）
6.重新启动rocketMQ服务器，客户端也同样无法连接

注：部分连接参数设置：  
m_tcpConnectTimeout = 400;        
m_tcpTransportTryLockTimeout = 3;  
![捕获](https://user-images.githubusercontent.com/58069189/69524995-251d0980-0fa2-11ea-8e99-d0b2f4054277.PNG)

7025_rocketmq-cpp.log.zip为日志文件

[7025_rocketmq-cpp.log.zip](https://github.com/apache/rocketmq-client-cpp/files/3884950/7025_rocketmq-cpp.log.zip)

**Comment by panyongxuan** [comment]
补充，版本 rocketmq-client-cpp-1.2.4，使用源码编译方式

**Comment by zengxiaobai** [comment]
I have met the same issue. And I solved this tmply by restart the client,becasue  sometimes consumer.shutdown will coredump.
Your error log is very much like mine, https://github.com/apache/rocketmq-client-cpp/issues/202

**Comment by panyongxuan** [comment]
> 
> 
> I have met the same issue. And I solved this tmply by restart the client,becasue sometimes consumer.shutdown will coredump.
> Your error log is very much like mine, #202

嗯，重新启动可以连接成功，但是重启客户端这个方法在实际中使用的时候不方便，因为这个方法的前提是上层应用侦测到TCP中断

**Comment by zengxiaobai** [comment]
I use gorutines to exec ’lsof -p pid -nP‘  in cycles to detect alive connections of 10911 port. Also program  should store the tasks to disk and rebuild tasks from disk when restarting the program（https://github.com/zengxiaobai/task-manage）. In my case,  restart action is not very often. 
I use the temply way above until I have time to read the source code of rocketmq-client-cpp lib and solve it.

**Comment by zengxiaobai** [comment]
> > I have met the same issue. And I solved this tmply by restart the client,becasue sometimes consumer.shutdown will coredump.
> > Your error log is very much like mine, #202
> 
> 嗯，重新启动可以连接成功，但是重启客户端这个方法在实际中使用的时候不方便，因为这个方法的前提是上层应用侦测到TCP中断

I use gorutines to exec ’lsof -p pid -nP‘ in cycles to detect alive connections of 10911 port. Also program should store the tasks to disk and rebuild tasks from disk when restarting the program（https://github.com/zengxiaobai/task-manage）. In my case, restart action is not very often.
I use the temply way above until I have time to read the source code of rocketmq-client-cpp lib and solve it.

**Comment by ifplusor** [comment]
这个问题应该是连接管理的逻辑在调用libevent时发生了死锁，我正在找bug触发的原因，但还没找到。
