### ISSUE TITLE
push-consumer start failed and coredump when one namesrv host cannot be resolve

### ISSUE THREAD

**Issue by zengxiaobai** [apache/rocketmq-client-cpp#205]
**BUG REPORT**

1. Please describe the issue you observed:
    I have configured three Namesrv server: 
    rocketmq1.xxx.com:9876;rocketmq2.xxx.com:9876;rocketmq3.xxx.com:9876;
    sometimes my client coredump with log following dumped in /var/log/message when starting.
    I wonder why client cannot be started  if one of the rocketmq namesrvs cannot be connected and 
    the others can be connected
```
Nov 27 10:21:13 localhost rocketxxx: consumer start failed, (0x8ded20,0xc420176010)
Nov 27 10:21:18 localhost rocketxxx: terminate called after throwing an instance of 'rocketmq::MQClientException'
Nov 27 10:21:18 localhost rocketxxx: what():  msg: Failed to resolve  host name(rocketmq2.xxx.com): nodename nor servname provided, or not known,error:-1,in file </home/zwb/rpm/rocketmq-client-cpp/rocketmq-client-cpp-use/src/transport/TcpTransport.cpp> line:103
Nov 27 10:21:18 localhost systemd: rocketxx.service: main process exited, code=killed, status=6/ABRT
```
I reproduced above in my test production. 
Notice: to reproduce it the test must make the dns nameserver(not rocketmq's namesrv)  down instead of an unresolved host name which dns nameserver can return result with no query item.

- What did you do (The steps to reproduce)?
   push-consumer config namesrv with 
   rocketmq1.xxx.com:9876;rocketmq2.xxx.com:9876;rocketmq3.xxx.com:9876;

   vi /etc/resolve.conf
  `nameserver 192.168.1.31`
  192.168.1.31 is my client's ip which donot listen port 53.

   vi /etc/hosts
  `namerserver-ip rocketmq1.xxx.com`
   make one of the rocketmq's namesrv can be connected and the other cannot be resolved because 
   dns nameserver down

   start the push consumer 

- What did you expect to see?
   client start success, but only connect with rocketmq1.xxx.com

- What did you see instead?
   start failed and coredump

2. Please tell us about your environment:

 - What is your OS?
    CENTOS7
 - What is your client version?
   1.2.4
 - What is your RocketMQ version?
   4.5.2
3. Other information (e.g. detailed explanation, logs, related issues, suggestions on how to fix, etc):
   catch the exception and connect next namesrv, start failed when all namesrv cannot be connected

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by ifplusor** [comment]
DefaultMQPushConsumer::start() will call MQClientFactory::updateTopicRouteInfoFromNameServer() -> ... -> TcpRemotingClient::invokeSync() -> ... -> TcpTransport::connect() -> TcpTransport::getInetAddr(). If host cannot be resolved, evutil_getaddrinfo() will return error, then throw MQClientException. In call chain, nobody catch the exception.

**Comment by ShannonDing** [comment]
it is better to keep the hostname right and try to catch exceptions on the instance starting.
