### ISSUE TITLE
The DestroyProducer function have a bug

### ISSUE THREAD

**Issue by wei56** [apache/rocketmq-client-cpp#212]
The issue tracker is **ONLY** used for the CPP/C client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**
1. example目录中 Producer.c 里面用到DestroyProducer函数会导致程序coredump
2. DestroyProducer函数在src/extern/CProducer.cpp中
delete reinterpret_cast<DefaultMQProducer*>(pProducer);
可能存在问题，应该修改为
delete reinterpret_cast<DefaultProducer*>(pProducer);
麻烦评估是否合理。
ps：修改后自行编译后该函数没有coredump了。

**Comment by ShannonDing** [comment]
yes, you are right, it is a bug here. could you please request a pr to fix it directly?

**Comment by ShannonDing** [comment]
close due to #213
