### ISSUE TITLE
[HELP]Prevent or catch the crash of c++ exception throwing

### ISSUE THREAD

**Issue by jinoschina** [apache/rocketmq-client-cpp#24]
Is there any way to prevent or catch the crash of c++ exception throw while using pure c?  
Such as no topic exception when calling  SendMessageSync from sample "Producer.c". 
Thank u very much.

**Comment by ShannonDing** [comment]
Got it, the exception thrown by CPP kernel will be raised to the system if it is not handled in C API. 
Currently, it is better to ensure the parameter correct as much as possible, In the next version, the exception thrown by the CPP kernel will be caught by default and returned to the caller of the C API in the form of an error code.
