### ISSUE TITLE
How to connect aliyun MQ?

### ISSUE THREAD

**Issue by BrentHuang** [apache/rocketmq-client-cpp#270]
version： 2.0.1

我的消费者（default push consumer）程序已经正确启动了，在阿里云rocketmq控制台上发送一条消息，我的消费者程序可以收到，这个是通的。

但是在阿里云rocketmq控制台上点“消费验证”，却一直是失败，我的消费者程序也没有收到消息。

并且通过阿里云规则引擎流转到阿里云rocketmq的消息，我的消费者程序也没有收到。

topic和group id都没有问题。

请问是什么原因呢，能帮忙分析一下吗？

**Comment by BrentHuang** [comment]
consumer.setNamesrvDomain(info.namesrv_domain);
这个namesrv_domain填什么呢？

**Comment by BrentHuang** [comment]
已经搞定，instance name是必填的。

**Comment by BrentHuang** [comment]
class RocketMQMsgListener : public rocketmq::MessageListenerConcurrently
{
public:
    RocketMQMsgListener() {}
    virtual ~RocketMQMsgListener() {}

    virtual rocketmq::ConsumeStatus consumeMessage(const std::vector<rocketmq::MQMessageExt>& msgs)
    {
        for (size_t i = 0; i < msgs.size(); ++i)
        {
            callback_(msgs[i].getTopic(), msgs[i].getTags(), msgs[i].getMsgId(), msgs[i].getBody());
        }

        return rocketmq::CONSUME_SUCCESS;
    }

请问，这个回调接口的参数是一个msg的vector，在其中我循环消费每一个消息，然后总体返回一个CONSUME_SUCCESS。那么如果有的消息消费失败了，有的消费成功了，怎么办呢？总体返回一个CONSUME_SUCCESS不行吧？对于每一个消息的具体消费情况，怎么给服务器答复呢？

**Comment by BrentHuang** [comment]
循环中，如果遇到消费失败的，就返回RECONSUME_LATER吗？该消息及其后的消息都会在下一次回调的时候传过来？

**Comment by bilinxing** [comment]
> 循环中，如果遇到消费失败的，就返回RECONSUME_LATER吗？该消息及其后的消息都会在下一次回调的时候传过来？

 同样的疑问，请问有人解答么

**Comment by ifplusor** [comment]
消费失败返回RECONSUME_LATER，消息会发回broker，过一段时间会重新消费。

**Comment by ifplusor** [comment]
> class RocketMQMsgListener : public rocketmq::MessageListenerConcurrently
> {
> public:
> RocketMQMsgListener() {}
> virtual ~RocketMQMsgListener() {}
> 
> ```
> virtual rocketmq::ConsumeStatus consumeMessage(const std::vector<rocketmq::MQMessageExt>& msgs)
> {
>     for (size_t i = 0; i < msgs.size(); ++i)
>     {
>         callback_(msgs[i].getTopic(), msgs[i].getTags(), msgs[i].getMsgId(), msgs[i].getBody());
>     }
> 
>     return rocketmq::CONSUME_SUCCESS;
> }
> ```
> 
> 请问，这个回调接口的参数是一个msg的vector，在其中我循环消费每一个消息，然后总体返回一个CONSUME_SUCCESS。那么如果有的消息消费失败了，有的消费成功了，怎么办呢？总体返回一个CONSUME_SUCCESS不行吧？对于每一个消息的具体消费情况，怎么给服务器答复呢？

单条失败的情形，目前没做特殊处理。可以再创建一个producer，手动发回broker。
