### ISSUE TITLE
start producer failed

### ISSUE THREAD

**Issue by morysky** [apache/rocketmq-client-cpp#288]
OS:CentOS Linux release 7.5.1804 (Core)

I am using GO-SDK，But When I start the producer encounter this error
[start producer failed]. This is returned by CGO, So I cannot see any other errmsg.

Please help me.

**Comment by morysky** [comment]
// Start the producer.
func (p *defaultProducer) Start() error {
	err := rmqError(C.StartProducer(p.cproduer))
	if err != NIL {
		return err
	}
	return nil
}

**Comment by ShannonDing** [comment]
logs at {home}/logs/rocketmq-cpp

**Comment by morysky** [comment]
> q

I am a RD User, My service is running by OP's deploy tools. (Maybe $HOME is /root or www): ( So I cannot get the proper log path...

**Comment by morysky** [comment]
I can run it on my develop Linux machine... But fails on this machine...

**Comment by morysky** [comment]
fmt.Println("i am starting the producer |" ,*C.GetLatestErrorMessage(), "|", err, p.cproduer)

**Comment by morysky** [comment]
i am starting the producer | 98 | start producer failed &{}

**Comment by morysky** [comment]
boost::filesystem::create_directories: Permission denied: "//logs/rocketmq-cpp"

Solved.

**Comment by HQ1363** [comment]
@morysky  请问 boost::filesystem::create_directories: Permission denied: "//logs/rocketmq-cpp" 这个报错是怎么解决的啊,  我也遇到了一样的问题
