### ISSUE TITLE
rocketmq-client-cpp/bin not found librocketmq.so, but found librocketmq.a 

### ISSUE THREAD

**Issue by wanghoneygit** [apache/rocketmq-client-cpp#294]
/Library/Developer/CommandLineTools/usr/bin/libtool: warning same member name (log.o) in output file used for input files: libevent.a(log.o) and: libevent_core.a(log.o) due to use of basename, truncation and blank padding
/Library/Developer/CommandLineTools/usr/bin/libtool: warning same member name (numeric.o) in output file used for input files: libboost_locale.a(numeric.o) and: libboost_locale.a(numeric.o) due to use of basename, truncation and blank padding
/Library/Developer/CommandLineTools/usr/bin/libtool: warning same member name (poll.o) in output file used for input files: libevent.a(poll.o) and: libevent_core.a(poll.o) due to use of basename, truncation and blank padding
/Library/Developer/CommandLineTools/usr/bin/libtool: warning same member name (select.o) in output file used for input files: libevent_core.a(select.o) and: libevent.a(select.o) due to use of basename, truncation and blank padding
/Library/Developer/CommandLineTools/usr/bin/libtool: warning same member name (signal.o) in output file used for input files: libevent.a(signal.o) and: libevent_core.a(signal.o) due to use of basename, truncation and blank padding
/Library/Developer/CommandLineTools/usr/bin/libtool: warning same member name (utf8_codecvt_facet.o) in output file used for input files: libboost_filesystem.a(utf8_codecvt_facet.o) and: libboost_wserialization.a(utf8_codecvt_facet.o) due to use of basename, truncation and blank padding
Md5 Hash RocketMQ After:
cd9ea98c539dd42480aee56a367aa462  librocketmq.a
Try to copy /Users/wang/rocketmq-client-cpp/tmp_static_package_dir/librocketmq.a to /Users/wang/rocketmq-client-cpp/bin/
############# Package static rocketmq library success.#############
Build success without executing unit tests.
![image](https://user-images.githubusercontent.com/20147781/77884488-c3461680-7297-11ea-8af6-940d4853adac.png)
![image](https://user-images.githubusercontent.com/20147781/77884520-cf31d880-7297-11ea-83f8-dea42a2831ff.png)

**Comment by ShannonDing** [comment]
here in the pictures, On the macOS platform, the library names xxx.dylib.
![image](https://user-images.githubusercontent.com/16487356/77884852-7151c080-7298-11ea-975d-4b8588bced21.png)
