### ISSUE TITLE
crash on ubuntu 18.04,  verson: 2.1.0

### ISSUE THREAD

**Issue by BrentHuang** [apache/rocketmq-client-cpp#310]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fe8b6220801 in __GI_abort () at abort.c:79
#2  0x00007fe8b6875957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fe8b687bab6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fe8b687baf1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fe8b687bd24 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fe8a872e90c in rocketmq::TcpTransport::getInetAddr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#7  0x00007fe8a872f69b in rocketmq::TcpTransport::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#8  0x00007fe8a8728c8d in rocketmq::TcpRemotingClient::CreateTransport(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#9  0x00007fe8a8729101 in rocketmq::TcpRemotingClient::CreateNameServerTransport(bool) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#10 0x00007fe8a8729331 in rocketmq::TcpRemotingClient::GetTransport(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#11 0x00007fe8a872b6a4 in rocketmq::TcpRemotingClient::invokeSync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocketmq::RemotingCommand&, int) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#12 0x00007fe8a8656a5a in rocketmq::MQClientAPIImpl::getTopicRouteInfoFromNameServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, rocketmq::SessionCredentials const&) ()
   from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#13 0x00007fe8a8665ec5 in rocketmq::MQClientFactory::updateTopicRouteInfoFromNameServer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocketmq::SessionCredentials const&, bool) ()
   from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#14 0x00007fe8a8669939 in rocketmq::MQClientFactory::updateTopicRouteInfo(boost::system::error_code&, boost::shared_ptr<boost::asio::basic_deadline_timer<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime>, boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > > >) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#15 0x00007fe8a866b219 in boost::asio::detail::wait_handler<boost::_bi::bind_t<void, boost::_mfi::mf2<void, rocketmq::MQClientFactory, boost::system::error_code&, boost::shared_ptr<boost::asio::basic_deadline_timer<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime>, boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > > > >, boost::_bi::list3<boost::_bi::value<rocketmq::MQClientFactory*>, boost::_bi::value<boost::system::error_code>, boost::_bi::value<boost::shared_ptr<boost::asio::basic_deadline_timer<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime>, boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> > > > > > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#16 0x00007fe8a867049a in boost::asio::detail::task_io_service::run(boost::system::error_code&) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#17 0x00007fe8a86691cf in rocketmq::MQClientFactory::startScheduledTask(bool) () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#18 0x00007fe8a877b08e in thread_proxy () from /home/hgc/service/release/scripts/../third_party/librocketmq.so
#19 0x00007fe8b6f6f6db in start_thread (arg=0x7fe89bf37700) at pthread_create.c:463
#20 0x00007fe8b630188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) q

**Comment by ifplusor** [comment]
Please check your network.

**Comment by BrentHuang** [comment]
网络有波动，也不能崩吧？
If the network fluctuates, you can't kill the process

**Comment by ifplusor** [comment]
> 网络有波动，也不能崩吧？
> If the network fluctuates, you can't kill the process

崩溃是因为dns解析失败，抛出的异常没有处理。这么做，一定程度上是提醒namesrv设置错误。

**Comment by BrentHuang** [comment]
您的出发点我明白，但是线上的服务器，网络一有波动就挂了，不能这么搞。

**Comment by ifplusor** [comment]
@BrentHuang See #311

**Comment by suiyuemanbu** [comment]
Very good, I had the same problem!
