### ISSUE TITLE
error: possibly undefined macro: AC_PROG_LIBTOOL

### ISSUE THREAD

**Issue by yiduwangkai** [apache/rocketmq-client-cpp#32]
my os is Ubuntu 16.04.2
i exec build.sh and i get the error : 
configure.ac:101: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
i donot know what this means

**Comment by jonnxu** [comment]
please install libtool before exec build.sh

**Comment by jonnxu** [comment]
please reference README

note: make sure the following compile tools or libraries have been installed before running the build script build.sh.
compile tools:
gcc-c++ 4.8.2: c++ compiler while need support C++11
cmake 2.8.0: build jsoncpp require it
automake 1.11.1: build libevent require it
autoconf 2.65: build libevent require it
libtool 2.2.6: build libevent require it
libraries:
bzip2-devel 1.0.6: boost depend it

**Comment by yiduwangkai** [comment]
sudo apt-get install autotools-dev
sudo apt-get install aclocal  
sudo apt-get install autotools-dev
sudo apt-get install aclocal
sudo apt-get install automake
sudo apt-get install aclocal
sudo apt-get install libz-dev
sudo apt-get install libbz2-dev
sudo apt-get install libboost-all-dev

![image](https://user-images.githubusercontent.com/16093572/50721032-50310d00-10f3-11e9-9110-3152f25138b4.png)
