### ISSUE TITLE
如何关闭 /root/logs/rocketmq-cpp日志

### ISSUE THREAD

**Issue by taroyutao** [apache/rocketmq-client-cpp#332]
python sdk 需要关闭或者设置日志打印的级别，因为底层依赖：client-cpp

https://github.com/apache/rocketmq-client-python/issues/92

所以这个日志打印的级别该如何设置？

**Comment by ifplusor** [comment]
There are APIs that can set the level of log, but can not disable log.

```c
ROCKETMQCLIENT_API int SetPushConsumerLogLevel(CPushConsumer* consumer, CLogLevel level);
ROCKETMQCLIENT_API int SetProducerLogLevel(CProducer* producer, CLogLevel level);
```
