### ISSUE TITLE
The version of  libevent in the README should be 2.1.11

### ISSUE THREAD

**Issue by bin1221** [apache/rocketmq-client-cpp#333]
The version of  libevent in the README should be 2.1.11 instead of 2.0.22. openssl-1.1 support is available in libevent-2.1 releases.

**Comment by ifplusor** [comment]
@kevinrsa You are right. Cloud you make a PR to fix it?

**Comment by vongosling** [comment]
@kevinrsa will you?

**Comment by kevinrsa** [comment]
I'm afraid not. It seems that openssl can download it first before installation.

**Comment by kevinrsa** [comment]
> @kevinrsa will you?
