### ISSUE TITLE
c++ Client how to reply from java producer.reqeust(msg, 30000)

### ISSUE THREAD

**Issue by genius77** [apache/rocketmq-client-cpp#336]
as titile:
**c++ client how to reply from java producer.reqeust(msg, 30000)?**

**Comment by ifplusor** [comment]
you can test https://github.com/ifplusor/rocketmq-client-cpp

**Comment by genius77** [comment]
> you can test https://github.com/ifplusor/rocketmq-client-cpp

能说具体点，在哪一个文件中有示例？
我这边是CPP Client， 如何与Java "[rocketmq-spring](https://github.com/apache/rocketmq-spring)" 项目中的 producer.reqeust(msg, 30000) 接上，我能收到来自它的消息，但是，无法回复它的消息?

**Comment by ifplusor** [comment]
当前官方库的主分支还不支持RR模式，我上上面发的是另一个经过重构的分支，跟官方cpp不完全兼容，RR的样例可以参考https://github.com/ifplusor/rocketmq-client-cpp/blob/re_dev/example/RequestReply.cpp

**Comment by ifplusor** [comment]
当前官方库的主分支还不支持RR模式，我上上面发的是另一个经过重构的分支，跟官方cpp不完全兼容，RR的样例可以参考https://github.com/ifplusor/rocketmq-client-cpp/blob/re_dev/example/RequestReply.cpp
