### ISSUE TITLE
reopen issue 293

### ISSUE THREAD

**Issue by zhangyulu** [apache/rocketmq-client-cpp#341]
#293 中描述的问题又出现了若干次
目前使用的版本是基于commit b29bf5b69eab187a813a4d7f59534a6375e32d25，然后将PR #300 中的修改手动merge进去（因为这两个版本之间改动较大，引入了ssl相关的功能，但是在我的环境中用不上）
具体的日志已经在原issue中列出
https://github.com/apache/rocketmq-client-cpp/issues/293#issuecomment-752312388
使用的是Push模式的顺序消息

**Comment by ifplusor** [comment]
这个问题继续在 #293 中讨论吧
