### ISSUE TITLE
Can not share MQClientInstance between consumer and producer for same topic

### ISSUE THREAD

**Issue by lirong-Lee** [apache/rocketmq-client-cpp#347]
re_dev when DefaultMQPushConsumer and DefaultMQProducer are started at the same time, DefaultMQPushConsumer reports an error log: 
"doRebalance, testConsumer, but the topic[testOrderMq] not exist."
Unable to pull message

DefaultMQProducer needs to be shutdown() before DefaultMQPushConsumer start()，DefaultMQPushConsumer can pull messages

**Comment by lirong-Lee** [comment]
MQClientInstance.cpp:432
```
if (topicRouteData != nullptr) {
        LOG_INFO_NEW("updateTopicRouteInfoFromNameServer has data");
        auto old = getTopicRouteData(topic);
        bool changed = topicRouteDataIsChange(old.get(), topicRouteData.get());

        if (changed) {
          LOG_INFO_NEW("updateTopicRouteInfoFromNameServer changed:{}", topic);

          // update broker addr
          const auto& brokerDatas = topicRouteData->broker_datas();
          for (const auto& bd : brokerDatas) {
            LOG_INFO_NEW("updateTopicRouteInfoFromNameServer changed with broker name:{}", bd.broker_name());
            addBrokerToAddrTable(bd.broker_name(), bd.broker_addrs());
          }

          // update publish info
          {
            TopicPublishInfoPtr publishInfo(topicRouteData2TopicPublishInfo(topic, topicRouteData));
            updateProducerTopicPublishInfo(topic, publishInfo);
          }

          // update subscribe info
          if (getConsumerTableSize() > 0) {
            std::vector<MQMessageQueue> subscribeInfo = topicRouteData2TopicSubscribeInfo(topic, topicRouteData);
            updateConsumerTopicSubscribeInfo(topic, subscribeInfo);
          }

          addTopicRouteData(topic, topicRouteData);    

        }
```
**Prodouct will addTopicRouteData, causing the consumer to come in and changed is false, and updateConsumerTopicSubscribeInfo will not be executed**

**Comment by ifplusor** [comment]
@lirong-Lee You need to wait 20 seconds, the consumer can do rebalance in the next round.

**Comment by ifplusor** [comment]
@lirong-Lee You can set a different instance name to the consumer to bypass this issue. And share MQClientInstance between consumer and producer is not recommended.

**Comment by lirong-Lee** [comment]
@ifplusor I cannot guarantee that I will not subscribe to the same topic during the process. Can this be fixed?

**Comment by ifplusor** [comment]
> @ifplusor I cannot guarantee that I will not subscribe to the same topic during the process. Can this be fixed?

There is no plan to fix this issue in the short term. Please set instance name to avoid sharing MQClientInstance between consumer and producer.

**Comment by lirong-Lee** [comment]
@ifplusor How to set the instance name?

**Comment by ifplusor** [comment]
Call ```consumer.set_instance_name("consumer_instance_name")``` or ```producer.set_instance_name("producer_instance_name")```
https://github.com/apache/rocketmq-client-cpp/blob/bfae5c2f10a9f7dd5c73c07c57adb229e467c99f/include/MQClientConfig.h#L50

**Comment by lirong-Lee** [comment]
@ifplusor thanks
