### ISSUE TITLE
Is there a implementation of MessageSelector.bySql in rocketmq-client-cpp?

### ISSUE THREAD

**Issue by cng3s** [apache/rocketmq-client-cpp#356]
I would like to use MessageSelector.bySql, but I can't find it in rocketmq-client-cpp.
So Is there a implementation of MessageSelector.bySql in rocketmq-client-cpp? 
If not, what is the best practices for accomplishing similar functions ?

**Comment by ifplusor** [comment]
@cng3s C++ SDK doesn't support sql92. If you want to filter messages, you need to subscribe to all messages and do it by yourself.

**Comment by cng3s** [comment]
I see. thanks for your help.

**Comment by cng3s** [comment]
@ifplusor May I ask one more question, does rocketMQ-java do Sql filter in the the consumer? Or in the broker?

**Comment by ifplusor** [comment]
@cng3s SQL92 power by broker.
