### ISSUE TITLE
support connecting clusters through domain?

### ISSUE THREAD

**Issue by WanZixin** [apache/rocketmq-client-cpp#359]
If so, how to use it? There is a risk of connecting the cluster through IP address, because the machine corresponding to IP address may be offline.

**Comment by ifplusor** [comment]
@WanZixin replace IP with domain, and remain port.

**Comment by WanZixin** [comment]
@ifplusor Do you mean to write like this？
```c++
SetPushConsumerNameServerDomain(consumer, "mydomain:9876");
```

**Comment by ifplusor** [comment]
@WanZixin 

```c
SetPushConsumerNameServerAddress(consumer, "mydomain:9876");
```

**Comment by WanZixin** [comment]
@ifplusor What scenarios are these two functions applied to please?
```c++
SetPushConsumerNameServerAddress(consumer, "mydomain:9876");
SetPushConsumerNameServerDomain(consumer, "mydomain:9876");
```

**Comment by ifplusor** [comment]
`SetPushConsumerNameServerDomain` is deprecated, it will do HTTP Get to fetch namesrv list. Use `SetPushConsumerNameServerAddress` only.

**Comment by WanZixin** [comment]
@ifplusor It's working. Thank you!
