### ISSUE TITLE
Is DefaultMQPullConsumer.pull thread safe? 

### ISSUE THREAD

**Issue by Frodez** [apache/rocketmq-client-cpp#360]
I need to use the function:
```
PullResult DefaultMQPullConsumer::pull(const MQMessageQueue& mq, const std::string& subExpression, int64 offset, int maxNums)
```
And I need it for concurrent use. I have navigated several issues, like #141 , but there is no information about whether this function is thread safe.

**Comment by ifplusor** [comment]
@Frodez It is thread-safe.

**Comment by Frodez** [comment]
> @Frodez It is thread-safe.

Thank you.
