### ISSUE TITLE
批量发送消息，服务器端仅收到一条

### ISSUE THREAD

**Issue by rooode** [apache/rocketmq-client-cpp#363]
服务器端版本号4.9.0
客户端版本号C++ 2.2.0
问题描述：
1.当客户端使用上述版本号发送批量消息时，服务器端仅可以接收到1条消息。
2.如果使用mater分支进行发送批量消息，服务器端可以正常收到多条。

**Comment by ifplusor** [comment]
@rooode 2.2.0和master之间没有批量发送相关的变更
