### ISSUE TITLE
build faild on Apple M1 arm

### ISSUE THREAD

**Issue by 180909** [apache/rocketmq-client-cpp#365]
The issue tracker is **ONLY** used for the CPP/C client (feature request of RocketMQ need to follow [RIP process](https://github.com/apache/rocketmq/wiki/RocketMQ-Improvement-Proposal)). Keep in mind, please check whether there is an existing same report before your raise a new one.

Alternately (especially if your communication is not a bug report), you can send mail to our [mailing lists](http://rocketmq.apache.org/about/contact/). We welcome any friendly suggestions, bug fixes, collaboration, and other improvements.

Please ensure that your bug report is clear and that it is complete. Otherwise, we may be unable to understand it or to reproduce it, either of which would prevent us from fixing the bug. We strongly recommend the report(bug report or feature request) could include some hints as to the following:

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
$ sh build.sh
- What did you expect to see?
build success
- What did you see instead?
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [test/rsa_complex] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [test/shlibloadtest] Error 1
make: *** [all] Error 2
2. Please tell us about your environment:

 - What is your OS?
apple M1
 - What is your client version?
latest
 - What is your RocketMQ version?
latest

**Comment by xdatcloud** [comment]
Hi , please try to build client with `re_dev` branch, follow instructions under #354 .

**Comment by 180909** [comment]
Thanks for your comment, and i succeeded to build on Apple M1.
