### ISSUE TITLE
Incorrect UtilAll::currentTimeMillis

### ISSUE THREAD

**Issue by lemonzone2010** [apache/rocketmq-client-cpp#38]
I send one message,but i found incorrent bornTimestamp.
[requestHeader->bornTimestamp](https://github.com/apache/rocketmq-client-cpp/blob/6b9349eaaf0c2c032dfdd2a2afaf202edab7411b/src/producer/DefaultMQProducer.cpp#L361)
```c
requestHeader->bornTimestamp = UtilAll::currentTimeMillis();
```
The following unix timestamp value is what i want. But i got incorrent currentTimeMillis by **UtilAll::currentTimeMillis**:
>current time:2018/12/25 19:41:53
>unix timestamp:1545738113705
>result of UtilAll::currentTimeMillis:70913705

[UtilAll::currentTimeMillis](https://github.com/apache/rocketmq-client-cpp/blob/6b9349eaaf0c2c032dfdd2a2afaf202edab7411b/src/common/UtilAll.cpp#L282)
```c
uint64_t UtilAll::currentTimeMillis() {
  boost::posix_time::ptime current_date_microseconds =
      boost::posix_time::microsec_clock::local_time();
  return current_date_microseconds.time_of_day().total_milliseconds();
}
```

**Comment by ShannonDing** [comment]
Fixed.
