### ISSUE TITLE
cann't set namesrv with hostname

### ISSUE THREAD

**Issue by lemonzone2010** [apache/rocketmq-client-cpp#42]
I try to set namesrv with host name ,but it doesn’t work:

>1. producer.setNamesrvAddr("name1.xxx.domain:9876;name2.xxx.domain:9876");
>2. producer.setNamesrvDomain("name1.xxx.domain:9876;name2.xxx.domain:9876");

And The following error occurred:

>Type: MQClientException , msg: No route info of this topic,  error:-1

It's ok only when i set namesrv with ip
>producer.setNamesrvAddr("192.168.0.1:9876;192.168.0.2:9876");

**Comment by ShannonDing** [comment]
Could you please check this issue? @jonnxu

**Comment by jonnxu** [comment]
@ShannonDing ok, this issue will analisys and resolve in version 1.2.2

**Comment by ifplusor** [comment]
bufferevent_socket_connect_hostname support dns

**Comment by wanliqun** [comment]
Maybe you can try domain name resolving before connecting.

  struct sockaddr_in sin;
  memset(&sin, 0, sizeof(sin));
  sin.sin_family = AF_INET;
  sin.sin_addr.s_addr = inet_addr(hostName.c_str());
  sin.sin_port = htons(portNumber);

  //////////////////////// Add these //////////////////////////
  if (INADDR_NONE == sin.sin_addr.s_addr) { // Invalid ip address, maybe it's a domain name
    try
    {
      boost::asio::io_service io_service;
      boost::asio::ip::tcp::resolver resolver(io_service);
      boost::asio::ip::tcp::resolver::query query(hostName, boost::lexical_cast<string>(portNumber));

      LOG_DEBUG("dns resolving for host name: %s, service name: %s", hostName.c_str(), query.service_name().c_str());
      boost::asio::ip::tcp::resolver::iterator iter = resolver.resolve(query);

      boost::asio::ip::tcp::endpoint endpoint = iter->endpoint();
      std::string ipAddr = endpoint.address().to_string();

      LOG_DEBUG("dns resolving endpoint: %s", ipAddr.c_str());
      sin.sin_addr.s_addr = inet_addr(ipAddr.c_str());
    } catch(const std::exception& e) {
      LOG_ERROR("dns resolving error: %s", e.what());
      return e_connectFail;
    }
  }
  //////////////////////// End Add //////////////////////////

  m_eventBase = event_base_new();
  m_bufferEvent = bufferevent_socket_new(
      m_eventBase, -1, BEV_OPT_CLOSE_ON_FREE | BEV_OPT_THREADSAFE);
  bufferevent_setcb(m_bufferEvent, readNextMessageIntCallback, NULL, eventcb,
                    this);
  bufferevent_enable(m_bufferEvent, EV_READ | EV_WRITE);
  bufferevent_setwatermark(m_bufferEvent, EV_READ, 4, 0);
