### ISSUE TITLE
Downloading dependent packages without checking certificate in compile shell.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq-client-cpp#436]
https://www.openssl.org/source/old/1.1.1/openssl-1.1.1d.tar.gz
Resolving www.openssl.org (www.openssl.org)... 23.65.230.47, 2600:1407:1d:38c::c1e, 2600:1407:1d:3a0::c1e
Connecting to www.openssl.org (www.openssl.org)|23.65.230.47|:443... connected.
ERROR: cannot verify www.openssl.org's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to www.openssl.org insecurely, use `--no-check-certificate'.
The command "./build.sh test codecov noVerbose" exited with 1.

**Comment by BeautyYuYanli** [comment]
[Update](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) system's ca-certificates from the package manager may fix this
