### ISSUE TITLE
v5.0-rc2 cannot connect to Apache RocketMQ - Version 5.0.0-ALPHA

### ISSUE THREAD

**Issue by lirong-Lee** [apache/rocketmq-client-cpp#442]
v5.0-rc2 cannot connect to Apache RocketMQ - Version 5.0.0-ALPHA, what version of broker can be connected?

**Comment by lizhanhui** [comment]
@lirong-Lee It works with the latest [develop](https://github.com/apache/rocketmq) branch, which will be released this week.

**Comment by lirong-Lee** [comment]
您好，您的邮件我已收到。

**Comment by lizhanhui** [comment]
One more thing, @lirong-Lee development of 5.x SDKs are moved to https://github.com/apache/rocketmq-clients/  Please use that repository for issues reporting and release downloads.
