### ISSUE TITLE
程序启动了两个Producer，程序退出时，关闭第二个Producer时 coredump

### ISSUE THREAD

**Issue by HUHANK** [apache/rocketmq-client-cpp#468]
**问题描述**：程序因业务需求启动了两个producer，一个consumer，consumer和第一个producer能成功关闭，关闭第二个producer时，发生段错误

**程序退出时日志**：
![image](https://github.com/apache/rocketmq-client-cpp/assets/9984283/4a6800cd-84b9-4459-a2c6-e3c80d0d4480)

**Coredump文件的调用堆栈信息**：
![image](https://github.com/apache/rocketmq-client-cpp/assets/9984283/f27223bd-64bd-4de1-a8f7-7d3695c5dede)

**rocketmq api打印的日志**：
![image](https://github.com/apache/rocketmq-client-cpp/assets/9984283/7b12032f-9240-4530-bac9-9b580735ce7d)

请大神帮忙看看这是什么问题，不胜感谢！@ifplusor

**Comment by ifplusor** [comment]
@HUHANK 相同 instance name 下的多个consumer/producer对象的 shutdown 不是线程安全的，我怀疑是遇到了并发问题。

**Comment by HUHANK** [comment]
> @HUHANK 相同 instance name 下的多个consumer/producer对象的 shutdown 不是线程安全的，我怀疑是遇到了并发问题。

我添加代码保证两个Producer一前一后关闭，崩溃的频率有降低，但是还是有崩溃，下面是崩溃的最新的调用堆栈信息：
![image](https://github.com/apache/rocketmq-client-cpp/assets/9984283/b485c1c0-9af2-4d43-9e01-3050ff6c337d)

异常我代码里面catch不到

**Comment by ifplusor** [comment]
@HUHANK consumer的关闭也要同步。建议你不同的对象使用不同的instance name，之样client_factory是独立的，相互不会有影响。

不过你这个错误栈的出现比较奇怪，我想象不出来这个lock为什么出错。因为从时序上看，io_service还在运行，说明consumer还没有unregister，也就意味着client_factory不会销毁，这里的lock不应该出错的。

**Comment by HUHANK** [comment]
@ifplusor 确实如您所说，设置不同的instance name之后程序停止就不会崩溃了，正常了，非常感谢！
💯
