### ISSUE TITLE
example/CMakeFiles/PushConsumer.dir/build.make:116: recipe for target '../bin/PushConsumer' failed

### ISSUE THREAD

**Issue by yiduwangkai** [apache/rocketmq-client-cpp#54]
sudo apt-get install autotools-dev
sudo apt-get install aclocal  
sudo apt-get install autotools-dev
sudo apt-get install aclocal
sudo apt-get install automake
sudo apt-get install aclocal
sudo apt-get install libz-dev
sudo apt-get install libbz2-dev
sudo apt-get install libboost-all-dev

i install dependency libraies，but when i exec the build.sh，there is a error , this look like the code has bug
![image](https://user-images.githubusercontent.com/16093572/50721032-50310d00-10f3-11e9-9110-3152f25138b4.png)

**Comment by ShannonDing** [comment]
Zlib was not installed in your system.  for the Ubuntu system, it is better to install the zlib-devel library before installing Boost.
I think "sudo apt-get install zlib1g-dev" is much better.

**Comment by yiduwangkai** [comment]
thx, i have solve that，the Community of client cpp help me
