### ISSUE TITLE
[bug]CMessageExt.GetMessageQueueOffset abnormal

### ISSUE THREAD

**Issue by githublaohu** [apache/rocketmq-client-cpp#86]
**BUG REPORT**

1. Please describe the issue you observed:
Get the right value。

- What did you do (The steps to reproduce)?
`
MQMessageExt *mqMessageExt = new MQMessageExt();
CMessageExt  *messageExt = (CMessageExt*)mqMessageExt;
mqMessageExt->setStoreTimestamp(123123);
GetMessageStoreTimestamp(messageExt);
`

- What did you expect to see?
CMessageExt.GetMessageStoreTimestamp == MQMessageExt.getStoreTimestamp

- What did you see instead?

**Comment by ShannonDing** [comment]
Fixed.
