### ISSUE TITLE
the librocketmq.so is much bigger than the dynamic lib in aliyun rocketmq cpp sdkdemo

### ISSUE THREAD

**Issue by elisium7** [apache/rocketmq-client-cpp#87]
i compile this cpp project, then i get librocketmq.so which is about 30M, and librocketmq.a is about 90M, it is too big for a client sdk. i set boost_use_static_libs switch on,libevent_use_static_libs off,jsoncpp_use_static_libs on, gcc version is 4.8.5.

can anyone tell me how can reduce the size of librocketmq.so and librocketmq.a get from the project?

**Comment by ifplusor** [comment]
now, default libs contain it's dependecies in single file. you can remove them by modify build script files to reduce file size.

**Comment by githublaohu** [comment]
你是否使用最新的版本，关于 .so 与 .a 文件过大已经解决了。
Whether you use the latest version or not, the excessive size of. so and. a files has been resolved.

**Comment by elisium7** [comment]
>           你是否使用最新的版本，关于 .so 与 .a 文件过大已经解决了。
> Whether you use the latest version or not, the excessive size of. so and. a files has been resolved.

ok,thanks ,I have confirmed ,can you tell me from what you did about to reduce the size.

**Comment by elisium7** [comment]
>           你是否使用最新的版本，关于 .so 与 .a 文件过大已经解决了。
> Whether you use the latest version or not, the excessive size of. so and. a files has been resolved.

ok ,thanks ,i have confirmed ,can you tell me what you did to reduce the size?

**Comment by jonnxu** [comment]
hi elisium7, i compile rocketmq-client-cpp by running build.sh with latest version, the size for library are:
librocketmq.a 22M
librocketmq.so 3M
if you change some parameter?

**Comment by jonnxu** [comment]
when using the default build.sh to build  library, the libraries will no depend on json, boost and libevent again,  you just need link rocketmq and also link with following libraries -lpthread -lz -ldl -lrt. Here is an example.
so i think there is no need to change the compile parameters
