### ISSUE TITLE
It will crash when start orderly push consumer.

### ISSUE THREAD

**Issue by powerfulsnail** [apache/rocketmq-client-cpp#89]
组网环境，当前3台服务器A(broker-a, broker-c-s)、B(broker-b, broker-a-s)、C(broker-c, broker-b-s)，同步复制，异步刷盘，发送顺序消息到一个master和同步到一个slave后，停掉master，创建消费者，订阅topic，注册顺序监听，启动顺序消费者时进程crash

**Comment by jonnxu** [comment]
which example program  you test,  cpp or c api?

**Comment by powerfulsnail** [comment]
一个master一个slave情况下，停掉master，顺序消费slave上的消息我这也没crash，
 但是 三个master与三个slave情况下，停掉之前顺序消息发往的broker的master，从slave上顺序消费时crash，下为对应栈信息
(gdb) bt
#0  0x00007ffff7aa6731 in rocketmq::TcpRemotingClient::GetTransport(std::string const&, bool) () from /usr/local/lib/librocketmq.so
#1  0x00007ffff7aa7964 in rocketmq::TcpRemotingClient::invokeSync(std::string const&, rocketmq::RemotingCommand&, int) () from /usr/local/lib/librocketmq.so
#2  0x00007ffff7a30e92 in rocketmq::MQClientAPIImpl::lockBatchMQ(std::string const&, rocketmq::LockBatchRequestBody*, std::vector<rocketmq::MQMessageQueue, std::allocator<rocketmq::MQMessageQueue> >&, int, rocketmq::SessionCredentials const&) () from /usr/local/lib/librocketmq.so
#3  0x00007ffff7a7b1c4 in rocketmq::Rebalance::lock(rocketmq::MQMessageQueue) () from /usr/local/lib/librocketmq.so
#4  0x00007ffff7a6deca in rocketmq::DefaultMQPushConsumer::pullMessageAsync(rocketmq::PullRequest*) () from /usr/local/lib/librocketmq.so
#5  0x00007ffff7a9f44b in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, boost::_mfi::mf2<void, rocketmq::taskBatchHandler, rocketmq::Task, long>, boost::_bi::list3<boost::_bi::value<rocketmq::taskBatchHandler*>, boost::_bi::value<rocketmq::Task>, boost::_bi::value<long> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
   from /usr/local/lib/librocketmq.so
#6  0x00007ffff7a439f1 in boost::asio::detail::task_io_service::run(boost::system::error_code&) () from /usr/local/lib/librocketmq.so
#7  0x00007ffff7a65516 in boost::asio::io_service::run() () from /usr/local/lib/librocketmq.so
#8  0x00007ffff7af62cf in thread_proxy () from /usr/local/lib/librocketmq.so
#9  0x00007ffff7703df5 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffff65f01ad in clone () from /lib64/libc.so.6
